"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { useEffect, useMemo, useRef, useState } from "react";
import { correctAnswer } from "./math-input";
import { warmupFor } from "./math-system";
import { collectible, completeSession, dateKey, parseProgress, startSession, type Outcome, type Progress, type Session } from "./progress";

type Screen="title"|"contents"|"warmupIntro"|"warmup"|"warmupComplete"|"challengeIntro"|"challenge"|"results"|"reward"|"study"|"rewards"|"settings";
const storageKey="neverending-math-progress-v2";
function spokenNumber(raw:string){const direct=raw.trim().replace(/−/g,"-").replace(/,/g,"");if(/^[-+]?\d+$/.test(direct))return direct;const words:Record<string,number>={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};let total=0,current=0,negative=false;for(const word of raw.toLowerCase().replace(/-/g," ").match(/[a-z]+/g)??[]){if(word==="negative"||word==="minus")negative=true;else if(word==="hundred")current=Math.max(1,current)*100;else if(word==="thousand"){total+=Math.max(1,current)*1000;current=0;}else if(words[word]!==undefined)current+=words[word];}return String((negative?-1:1)*(total+current));}

export default function Home(){
 const [screen,setScreen]=useState<Screen>("title"),[progress,setProgress]=useState<Progress>(()=>parseProgress(null)),[session,setSession]=useState<Session|null>(null);
 const [warmIndex,setWarmIndex]=useState(0),[questionIndex,setQuestionIndex]=useState(0),[attempts,setAttempts]=useState(0),[outcomes,setOutcomes]=useState<Outcome[]>([]);
 const [answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[detail,setDetail]=useState(""),[listening,setListening]=useState(false),[loaded,setLoaded]=useState(false),[inspect,setInspect]=useState<string|null>(null);
 const inputRef=useRef<HTMLInputElement>(null),recognitionRef=useRef<any>(null),today=dateKey();
 const warmups=useMemo(()=>session?warmupFor(session.dateKey,session.serial):[],[session]),activeQuestion=session?.questions[questionIndex];
 const completeToday=progress.sessions.some(item=>item.dateKey===today&&item.complete);
 useEffect(()=>{if(new URLSearchParams(location.search).get("reset")==="1"){localStorage.removeItem(storageKey);history.replaceState({},"",location.pathname);}setProgress(parseProgress(localStorage.getItem(storageKey)));setLoaded(true);},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(storageKey,JSON.stringify(progress));},[loaded,progress]);
 useEffect(()=>{if((screen==="warmup"||screen==="challenge"))inputRef.current?.focus();},[screen,warmIndex,questionIndex]);
 useEffect(()=>()=>{try{recognitionRef.current?.abort();}catch{}},[]);
 function tone(kind:"tap"|"right"|"wrong"|"bell"|"place"){if(!progress.sound)return;const AC=window.AudioContext||(window as any).webkitAudioContext;if(!AC)return;const c=new AC(),o=c.createOscillator(),g=c.createGain(),f={tap:240,right:660,wrong:120,bell:880,place:180}[kind];o.frequency.value=f;o.type=kind==="right"||kind==="bell"?"sine":"triangle";g.gain.setValueAtTime(kind==="bell"?.08:.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+(kind==="bell"?1.2:.25));o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+(kind==="bell"?1.2:.25));}
 function go(next:Screen){tone("tap");try{recognitionRef.current?.abort();}catch{}recognitionRef.current=null;setListening(false);setFeedback("");setDetail("");setAnswer("");setScreen(next);}
 function begin(extra=false){const started=startSession(progress,today,extra);setProgress(started.progress);setSession(started.session);setWarmIndex(0);setQuestionIndex(0);setAttempts(0);setOutcomes([]);go("warmupIntro");}
 function finishWarm(correct:boolean,heard=""){const question=warmups[warmIndex];if(!question)return;if(correct){tone("right");setFeedback("✓  CORRECT");setDetail(heard?`I heard “${heard}.”`:"");setTimeout(()=>{if(warmIndex===warmups.length-1)go("warmupComplete");else{setWarmIndex(v=>v+1);setAttempts(0);setFeedback("");setDetail("");setAnswer("");}},600);}else if(attempts===0){tone("wrong");setAttempts(1);setFeedback("TRY ONCE MORE");setDetail("Take another quiet moment with it.");setAnswer("");}else{tone("tap");setFeedback(question.shown);setDetail("Keep that fact for another day.");setTimeout(()=>{if(warmIndex===warmups.length-1)go("warmupComplete");else{setWarmIndex(v=>v+1);setAttempts(0);setFeedback("");setDetail("");setAnswer("");}},1150);}}
 function submitWarm(raw=answer){const question=warmups[warmIndex];if(question&&raw.trim())finishWarm(correctAnswer(question,raw),raw);}
 function listen(){if(listening||recognitionRef.current)return;if(!progress.voice||!window.isSecureContext){setFeedback(!progress.voice?"VOICE INPUT IS TURNED OFF":"VOICE INPUT REQUIRES A SECURE CONNECTION");setDetail("Type the answer instead.");return;}const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R){setFeedback("VOICE INPUT ISN’T AVAILABLE HERE");setDetail("Type the answer instead.");return;}const r=new R();recognitionRef.current=r;r.lang="en-US";r.continuous=false;r.interimResults=false;const stop=()=>{recognitionRef.current=null;setListening(false);};r.onstart=()=>{setListening(true);setFeedback("LISTENING…");setDetail("Say the answer clearly.");};r.onresult=(event:any)=>{const heard=String(event.results?.[0]?.[0]?.transcript??"").trim();stop();if(heard)submitWarm(spokenNumber(heard));else{setFeedback("I COULDN’T HEAR AN ANSWER");setDetail("Type it instead.");}};r.onerror=()=>{stop();setFeedback("VOICE INPUT ISN’T AVAILABLE RIGHT NOW");setDetail("Type the answer instead.");};r.onend=stop;try{r.start();}catch{stop();}}
 function advance(outcome:Outcome){const next=[...outcomes,outcome];setOutcomes(next);setTimeout(()=>{if(questionIndex===(session?.questions.length??1)-1)go("results");else{setQuestionIndex(v=>v+1);setAttempts(0);setAnswer("");setFeedback("");setDetail("");}},700);}
 function submitQuestion(){if(!activeQuestion||!answer.trim())return;if(correctAnswer(activeQuestion,answer)){tone("right");setFeedback("✓  CORRECT");advance(attempts===0?"first":"retry");}else if(attempts===0){tone("wrong");setAttempts(1);setFeedback("NOT QUITE — TRY ONCE MORE");setDetail(activeQuestion.hint);setAnswer("");}else{tone("wrong");setFeedback("LET’S REVIEW IT");setDetail(activeQuestion.shown);}}
 function receive(){if(!session)return;const next=completeSession(progress,session.id,outcomes);setProgress(next);setSession(next.sessions.find(item=>item.id===session.id)??session);tone("bell");go("reward");}
 function place(id:string){if(progress.placedIds.includes(id))return;setProgress(value=>({...value,placedIds:[...value.placedIds,id]}));tone("place");setInspect(id);}
 const reward=session?.rewardId?collectible(session.rewardId):null,counts={first:outcomes.filter(x=>x==="first").length,retry:outcomes.filter(x=>x==="retry").length,reviewed:outcomes.filter(x=>x==="reviewed").length};
 const image=(name:string,children:React.ReactNode,label:string)=><section className={`stage image-stage ${name}`} aria-label={label}><img src={`/assets/${name}.png`} alt="" draggable={false}/>{children}</section>;
 return <main className="game-shell"><div className="grain" aria-hidden="true"/>
 {screen==="title"&&image("title",<>{completeToday&&<div className="completion-mark">TODAY’S ROOM REMEMBERS</div>}<button className="hotspot start-hotspot" onClick={()=>go("contents")} aria-label="Enter Neverending Math"/></>,"Neverending Math")}
 {screen==="contents"&&image("contents",<><button className="hotspot daily-hotspot" onClick={()=>begin(false)} aria-label="Begin today’s mathematics"/><button className="hotspot rewards-hotspot" onClick={()=>go("rewards")} aria-label="Open objects collection"/><button className="hotspot settings-hotspot" onClick={()=>go("settings")} aria-label="Open settings"/>{completeToday&&<><div className="daily-status">✓ TODAY COMPLETE · RETURN TOMORROW</div><button className="extra-practice" onClick={()=>begin(true)}>PRACTICE A LITTLE MORE</button></>}<button className="corner-back" onClick={()=>go("title")}>← TITLE</button></>,"Contents")}
 {screen==="warmupIntro"&&<section className="stage image-stage art-transition-stage warm-transition-stage"><img src="/assets/warmup-clean.png" alt=""/><div className="warm-transition-copy"><p>EIGHT QUICK FACTS.</p><p>SAY OR TYPE EACH ANSWER.</p></div><button className="art-chalk-button warm-transition-button" onClick={()=>go("warmup")}>BEGIN →</button></section>}
 {screen==="warmup"&&<section className="stage image-stage warm-art-stage"><img src="/assets/warmup-clean.png" alt=""/><p className="warm-live-count">{warmIndex+1} OF {warmups.length}</p><div className="warm-live-problem fact-medium">{warmups[warmIndex]?.prompt.replace(" = ?","")}</div><button className={`mic-hotspot ${listening?"listening":""}`} onClick={listen} aria-label="Use voice input"/><div className="voice-state" aria-live="polite"><strong>{feedback||"SAY IT ALOUD, OR TYPE IT BELOW"}</strong><span>{detail}</span></div><form className="warm-type-form" onSubmit={e=>{e.preventDefault();submitWarm();}}><input ref={inputRef} value={answer} onChange={e=>setAnswer(e.target.value)} inputMode="numeric" aria-label="Warm-up answer"/><button>CHECK →</button></form></section>}
 {screen==="warmupComplete"&&<section className="stage image-stage art-transition-stage warm-transition-stage"><img src="/assets/warmup-clean.png" alt=""/><div className="warm-transition-copy complete"><h1>WARM-UP COMPLETE</h1><p>THE DAILY CHALLENGE IS READY.</p></div><button className="art-chalk-button warm-transition-button" onClick={()=>go("challengeIntro")}>CONTINUE →</button></section>}
 {screen==="challengeIntro"&&<section className="stage image-stage art-transition-stage challenge-transition-stage"><img src="/assets/challenge-clean.png" alt=""/><div className="challenge-transition-copy"><p className="challenge-day">TODAY’S SESSION</p><h1>DAILY CHALLENGE</h1><p className="challenge-total">{session?.questions.length??12} QUESTIONS</p><p className="challenge-intro-note">Take your time. Difficult questions are meant to be worked out.</p></div><button className="art-chalk-button challenge-transition-button" onClick={()=>go("challenge")}>BEGIN →</button></section>}
 {screen==="challenge"&&activeQuestion&&<section className="stage image-stage challenge-art-stage"><img src="/assets/challenge-clean.png" alt=""/><p className="challenge-live-count">QUESTION {questionIndex+1} OF {session?.questions.length}</p><p className="challenge-live-rule">— {activeQuestion.skill.replace(/([A-Z])/g," $1").toUpperCase()} —</p><div className={`challenge-live-question ${activeQuestion.prompt.length>30?"challenge-sentence":"challenge-expression"}`}>{activeQuestion.prompt}</div><form className="challenge-answer-form" onSubmit={e=>{e.preventDefault();feedback==="LET’S REVIEW IT"?advance("reviewed"):submitQuestion();}}><label htmlFor="main-answer">YOUR ANSWER</label><input id="main-answer" ref={inputRef} value={answer} onChange={e=>setAnswer(e.target.value)} autoComplete="off" inputMode={activeQuestion.input==="number"?"numeric":"text"} disabled={feedback==="LET’S REVIEW IT"}/><button>{feedback==="LET’S REVIEW IT"?"CONTINUE →":"CHECK ANSWER →"}</button></form>{activeQuestion.input==="factors"&&<p className="challenge-format-example">FORMAT: 2 × 2 × 3</p>}<button className="challenge-skip" onClick={()=>{setFeedback("LET’S REVIEW IT");setDetail(activeQuestion.shown);}}>SKIP</button><div className="challenge-feedback" aria-live="polite"><strong>{feedback}</strong><span>{detail}</span></div></section>}
 {screen==="results"&&<section className="stage chalk-stage results-stage"><p className="eyebrow">NEVERENDING MATH</p><h1>TODAY’S WORK<br/>IS COMPLETE</h1><div className="score-grid"><p><b>{counts.first}</b>CORRECT</p><p><b>{counts.retry}</b>SOLVED WITH<br/>ANOTHER TRY</p><p><b>{counts.reviewed}</b>REVIEWED</p></div><div className="completion-list"><span>✓ WARM-UP COMPLETE</span><span>✓ DAILY CHALLENGE COMPLETE</span></div>{counts.reviewed>0&&<p className="review-note">A few ideas have been left on the board for another day.</p>}<p className="room-notice">The room has noticed your work.</p><button className="chalk-button results-reward-button" onClick={receive}>RECEIVE TODAY’S OBJECT →</button></section>}
 {screen==="reward"&&image("reward-clean",<><div className="reward-glow"/><div className="reward-name"><strong>{reward?.[1]}</strong><span>{reward?.[2]}</span></div><button className="reward-choice reward-continue" onClick={()=>go("rewards")}>CONTINUE TO OBJECTS COLLECTION →</button><button className="reward-choice reward-home" onClick={()=>go("title")}>GO HOME</button></>,"Object found")}
 {screen==="rewards"&&image("rewards",<><div className="locked-collection-grid"/><div className="found-count">{progress.collectedIds.length} / 30 FOUND</div><div className="collection-items">{progress.collectedIds.slice(-8).map(id=><button key={id} className="collection-item" onClick={()=>setInspect(id)}>{collectible(id)[1]}</button>)}</div>{inspect&&<><div className="collection-label"><strong>{collectible(inspect)[1]}</strong><span>{collectible(inspect)[2]}</span></div><button className="collection-study-button" onClick={()=>go("study")}>{progress.placedIds.includes(inspect)?"VIEW IN THE STUDY →":"PLACE IN THE STUDY →"}</button></>}<button className="hotspot rewards-back" onClick={()=>go("contents")} aria-label="Return to contents"/></>,"Objects collection")}
 {screen==="study"&&image("study-empty",<><div className="study-objects">{progress.placedIds.map((id,index)=><button key={id} className={`study-object study-object-${index%8}`} onClick={()=>setInspect(id)}>{collectible(id)[1]}</button>)}</div>{inspect&&<div className="object-label"><strong>{collectible(inspect)[1]}</strong><span>{collectible(inspect)[2]}</span></div>}{inspect&&!progress.placedIds.includes(inspect)&&<button className="study-place-button" onClick={()=>place(inspect)}>PLACE THIS IN THE STUDY →</button>}<button className="hotspot study-back-hotspot" onClick={()=>go("rewards")} aria-label="Return to collection"/><button className="study-home" onClick={()=>go("title")}>GO HOME</button></>,"The Study")}
 {screen==="settings"&&image("settings",<><div className="settings-controls"><button onClick={()=>setProgress(v=>({...v,voice:!v.voice}))}>VOICE: {progress.voice?"ON":"OFF"}</button><button onClick={()=>setProgress(v=>({...v,sound:!v.sound}))}>SOUND: {progress.sound?"ON":"OFF"}</button></div><button className="hotspot settings-back" onClick={()=>go("contents")} aria-label="Back"/><button className="hotspot settings-save" onClick={()=>go("contents")} aria-label="Save settings"/></>,"Settings")}
 </main>;
}
