"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, @next/next/no-img-element */
import { useEffect, useRef, useState } from "react";
import { collectible, objectGlyphs } from "./collectibles";
import { correctAnswer } from "./math-input";
import { skillGroups, skillNames, type SkillId } from "./math-system";
import { questionDisplay } from "./question-display";
import { checkpointSession, completeSession, dateKey, parseProgress, setSkillEnabled, startSession, type AnswerState, type JourneyPhase, type Outcome, type Progress, type Session } from "./progress";
import { voiceRecovery } from "./voice-policy";

type Screen="title"|"contents"|"warmupIntro"|"warmup"|"warmupComplete"|"challengeIntro"|"challenge"|"results"|"reward"|"study"|"rewards"|"settings";
type InteractionState=AnswerState|"advancing";
const storageKey="neverending-math-progress-v2";
function spokenNumber(raw:string){const direct=raw.trim().replace(/−/g,"-").replace(/,/g,"");if(/^[-+]?\d+$/.test(direct))return direct;const words:Record<string,number>={zero:0,one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10,eleven:11,twelve:12,thirteen:13,fourteen:14,fifteen:15,sixteen:16,seventeen:17,eighteen:18,nineteen:19,twenty:20,thirty:30,forty:40,fifty:50,sixty:60,seventy:70,eighty:80,ninety:90};let total=0,current=0,negative=false;for(const word of raw.toLowerCase().replace(/-/g," ").match(/[a-z]+/g)??[]){if(word==="negative"||word==="minus")negative=true;else if(word==="hundred")current=Math.max(1,current)*100;else if(word==="thousand"){total+=Math.max(1,current)*1000;current=0;}else if(words[word]!==undefined)current+=words[word];}return String((negative?-1:1)*(total+current));}

export default function Home(){
 const [screen,setScreen]=useState<Screen>("title"),[progress,setProgress]=useState<Progress>(()=>parseProgress(null)),[session,setSession]=useState<Session|null>(null);
 const [warmIndex,setWarmIndex]=useState(0),[questionIndex,setQuestionIndex]=useState(0),[attempts,setAttempts]=useState(0),[outcomes,setOutcomes]=useState<Outcome[]>([]),[answerState,setAnswerState]=useState<InteractionState>("answering");
 const [answer,setAnswer]=useState(""),[feedback,setFeedback]=useState(""),[detail,setDetail]=useState(""),[listening,setListening]=useState(false),[loaded,setLoaded]=useState(false),[inspect,setInspect]=useState<string|null>(null),[pendingPlacementId,setPendingPlacementId]=useState<string|null>(null);
 const inputRef=useRef<HTMLInputElement>(null),recognitionRef=useRef<any>(null),voiceRunRef=useRef(false),voiceFailuresRef=useRef(0),restartTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null),transitionTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null),transitionVersionRef=useRef(0),interactionLockRef=useRef(false),sessionRef=useRef<Session|null>(null),listenRef=useRef<()=>void>(()=>{}),screenRef=useRef<Screen>("title"),today=dateKey();
 const warmups=session?.warmups??[],activeQuestion=session?.questions[questionIndex],activeQuestionDisplay=activeQuestion?questionDisplay(activeQuestion):"expression";
 const completeToday=progress.sessions.some(item=>item.dateKey===today&&item.complete);
 // Browser storage cannot be read during server rendering; hydrate it once here.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(new URLSearchParams(location.search).get("reset")==="1"){localStorage.removeItem(storageKey);history.replaceState({},"",location.pathname);}setProgress(parseProgress(localStorage.getItem(storageKey)));setLoaded(true);},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(storageKey,JSON.stringify(progress));},[loaded,progress]);
 useEffect(()=>{screenRef.current=screen;},[screen]);
 useEffect(()=>{sessionRef.current=session;},[session]);
 useEffect(()=>{if((screen==="warmup"||screen==="challenge"))inputRef.current?.focus();},[screen,warmIndex,questionIndex]);
 useEffect(()=>()=>{cancelTransition();stopVoice();},[]);
 function tone(kind:"tap"|"right"|"wrong"|"bell"|"place"){if(!progress.sound)return;const AC=window.AudioContext||(window as any).webkitAudioContext;if(!AC)return;const c=new AC(),o=c.createOscillator(),g=c.createGain(),f={tap:240,right:660,wrong:120,bell:880,place:180}[kind];o.frequency.value=f;o.type=kind==="right"||kind==="bell"?"sine":"triangle";g.gain.setValueAtTime(kind==="bell"?.08:.04,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+(kind==="bell"?1.2:.25));o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+(kind==="bell"?1.2:.25));}
 function stopVoice(){voiceRunRef.current=false;if(restartTimerRef.current)clearTimeout(restartTimerRef.current);restartTimerRef.current=null;try{recognitionRef.current?.abort();}catch{}recognitionRef.current=null;setListening(false);}
 function pauseVoiceForReview(){if(restartTimerRef.current)clearTimeout(restartTimerRef.current);restartTimerRef.current=null;try{recognitionRef.current?.abort();}catch{}recognitionRef.current=null;setListening(false);}
 function queueVoiceRestart(delay=500){if(!voiceRunRef.current)return;if(restartTimerRef.current)clearTimeout(restartTimerRef.current);restartTimerRef.current=setTimeout(()=>{restartTimerRef.current=null;if(voiceRunRef.current&&screenRef.current==="warmup")listenRef.current();},delay);}
 function cancelTransition(){transitionVersionRef.current+=1;if(transitionTimerRef.current)clearTimeout(transitionTimerRef.current);transitionTimerRef.current=null;interactionLockRef.current=false;}
 function scheduleTransition(expectedSessionId:string,expectedScreen:Screen,delay:number,run:()=>void){const version=transitionVersionRef.current;transitionTimerRef.current=setTimeout(()=>{if(version!==transitionVersionRef.current||sessionRef.current?.id!==expectedSessionId||screenRef.current!==expectedScreen)return;transitionTimerRef.current=null;run();},delay);}
 function acquireInteraction(){if(interactionLockRef.current)return false;interactionLockRef.current=true;return true;}
 function releaseInteraction(){interactionLockRef.current=false;}
 function go(next:Screen){cancelTransition();tone("tap");if(next!=="warmup")stopVoice();setFeedback("");setDetail("");setAnswer("");setScreen(next);}
 function checkpointState(saved:Session["checkpoint"]):AnswerState{return saved?.answerState==="retry"||saved?.answerState==="review"?saved.answerState:"answering";}
 function restoreCheckpoint(nextSession:Session){const saved=nextSession.checkpoint,state=checkpointState(saved),warm=nextSession.warmups[saved?.warmIndex??0],question=nextSession.questions[saved?.questionIndex??0];setWarmIndex(saved?.warmIndex??0);setQuestionIndex(saved?.questionIndex??0);setAttempts(saved?.attempts??(state==="retry"?1:state==="review"?2:0));setOutcomes(saved?.outcomes??[]);setAnswerState(state);if(state==="retry"){setFeedback(saved?.phase==="warmup"?"TRY ONCE MORE":"NOT QUITE — TRY ONCE MORE");setDetail(saved?.phase==="warmup"?"Take another quiet moment with it.":question?.hint??"");}else if(state==="review"){setFeedback(saved?.phase==="warmup"?warm?.shown??"":"LET’S REVIEW IT");setDetail(saved?.phase==="warmup"?"Keep that fact for another day.":question?.shown??"");}else{setFeedback("");setDetail("");}}
 function begin(extra=false){cancelTransition();const started=startSession(progress,today,extra),saved=started.session.checkpoint;setProgress(started.progress);setSession(started.session);go(saved?.phase??"warmupIntro");restoreCheckpoint(started.session);}
 function saveJourney(phase:JourneyPhase,warm=warmIndex,question=questionIndex,answers=outcomes,state:AnswerState="answering",tries=0){if(!session)return;setProgress(value=>checkpointSession(value,session.id,{phase,warmIndex:warm,questionIndex:question,outcomes:answers,answerState:state,attempts:tries}));}
 function toggleSkill(skill:SkillId){setProgress(value=>setSkillEnabled(value,skill,!value.activeSkills.includes(skill)));}
 function moveWarm(){if(!session)return;if(warmIndex===warmups.length-1){go("warmupComplete");return;}setWarmIndex(v=>v+1);setAttempts(0);setAnswerState("answering");setFeedback("");setDetail("");setAnswer("");releaseInteraction();queueVoiceRestart(450);}
 function checkpointNextWarm(){if(!session)return;const final=warmIndex===warmups.length-1;saveJourney(final?"warmupComplete":"warmup",final?warmIndex:warmIndex+1,questionIndex,outcomes,"answering",0);}
 function finishWarm(correct:boolean,heard=""){const question=warmups[warmIndex];if(!question||!acquireInteraction())return;if(correct){tone("right");setFeedback("✓  CORRECT");setDetail(heard?`I heard “${heard}.”`:"");checkpointNextWarm();setAnswerState("advancing");scheduleTransition(session!.id,"warmup",650,moveWarm);}else if(attempts===0){tone("wrong");setAttempts(1);setAnswerState("retry");setFeedback("TRY ONCE MORE");setDetail("Take another quiet moment with it.");setAnswer("");saveJourney("warmup",warmIndex,questionIndex,outcomes,"retry",1);releaseInteraction();queueVoiceRestart(900);}else{tone("tap");pauseVoiceForReview();setAttempts(2);setAnswerState("review");setFeedback(question.shown);setDetail("Keep that fact for another day.");setAnswer("");saveJourney("warmup",warmIndex,questionIndex,outcomes,"review",2);releaseInteraction();}}
 function continueWarm(){if(answerState!=="review"||!acquireInteraction())return;checkpointNextWarm();moveWarm();}
 function submitWarm(raw=answer,fromVoice=false){const question=warmups[warmIndex];if(answerState==="review"){if(!fromVoice)continueWarm();return;}if(answerState==="advancing")return;if(!fromVoice&&recognitionRef.current){try{recognitionRef.current.abort();}catch{}recognitionRef.current=null;setListening(false);}if(question&&raw.trim())finishWarm(correctAnswer(question,raw),raw);}
 function listen(){if(listening||recognitionRef.current)return;voiceRunRef.current=true;if(!progress.voice||!window.isSecureContext){stopVoice();setFeedback(!progress.voice?"VOICE INPUT IS TURNED OFF":"VOICE INPUT REQUIRES A SECURE CONNECTION");setDetail("Type the answer instead.");return;}const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R){stopVoice();setFeedback("VOICE INPUT ISN’T AVAILABLE HERE");setDetail("Type the answer instead.");return;}const r=new R();recognitionRef.current=r;r.lang="en-US";r.continuous=false;r.interimResults=false;let failed=false;const stop=()=>{if(recognitionRef.current===r)recognitionRef.current=null;setListening(false);};r.onstart=()=>{setListening(true);setFeedback("LISTENING…");setDetail("Voice will continue through the warm-up. Type at any time.");};r.onresult=(event:any)=>{voiceFailuresRef.current=0;const heard=String(event.results?.[0]?.[0]?.transcript??"").trim();stop();if(heard)submitWarm(spokenNumber(heard),true);else{setFeedback("I COULDN’T HEAR AN ANSWER");setDetail("Type it instead.");queueVoiceRestart(750);}};r.onerror=(event:any)=>{failed=true;stop();voiceFailuresRef.current+=1;if(voiceRecovery(String(event.error),voiceFailuresRef.current)==="typing"){stopVoice();setFeedback("VOICE INPUT ISN’T AVAILABLE RIGHT NOW");setDetail("Typing is ready below.");}else{setFeedback("LISTENING PAUSED");setDetail("I’ll try once more. You can type instead.");queueVoiceRestart(800);}};r.onend=()=>{stop();if(!failed&&voiceRunRef.current)setDetail(value=>value||"Type an answer, or tap the microphone to listen again.");};try{r.start();}catch{stopVoice();setFeedback("VOICE INPUT ISN’T AVAILABLE RIGHT NOW");setDetail("Typing is ready below.");}}
 listenRef.current=listen;
 function advanceQuestion(outcome:Outcome){if(!session)return;const next=[...outcomes,outcome],final=questionIndex===session.questions.length-1;setOutcomes(next);saveJourney(final?"results":"challenge",warmIndex,final?questionIndex:questionIndex+1,next,"answering",0);setAnswerState("advancing");scheduleTransition(session.id,"challenge",700,()=>{if(final){go("results");return;}setQuestionIndex(v=>v+1);setAttempts(0);setAnswerState("answering");setAnswer("");setFeedback("");setDetail("");releaseInteraction();});}
 function enterQuestionReview(){if(!activeQuestion)return;tone("wrong");setAttempts(2);setAnswerState("review");setFeedback("LET’S REVIEW IT");setDetail(activeQuestion.shown);setAnswer("");saveJourney("challenge",warmIndex,questionIndex,outcomes,"review",2);}
 function showQuestionReview(){if(!activeQuestion||answerState==="review"||answerState==="advancing"||!acquireInteraction())return;enterQuestionReview();releaseInteraction();}
 function continueQuestion(){if(answerState!=="review"||!acquireInteraction())return;advanceQuestion("reviewed");}
 function submitQuestion(){if(answerState==="review"){continueQuestion();return;}if(answerState==="advancing"||!activeQuestion||!answer.trim()||!acquireInteraction())return;if(correctAnswer(activeQuestion,answer)){tone("right");setFeedback("✓  CORRECT");advanceQuestion(attempts===0?"first":"retry");}else if(attempts===0){tone("wrong");setAttempts(1);setAnswerState("retry");setFeedback("NOT QUITE — TRY ONCE MORE");setDetail(activeQuestion.hint);setAnswer("");saveJourney("challenge",warmIndex,questionIndex,outcomes,"retry",1);releaseInteraction();}else{enterQuestionReview();releaseInteraction();}}
 function receive(){if(!session)return;const next=completeSession(progress,session.id,outcomes),finished=next.sessions.find(item=>item.id===session.id)??session;setProgress(next);setSession(finished);if(finished.rewardId){tone("bell");go("reward");}else go("study");}
 function beginPlacement(id:string){if(!progress.collectedIds.includes(id))return;setInspect(id);setPendingPlacementId(progress.placedIds.includes(id)?null:id);go("study");}
 function place(id:string){if(!progress.collectedIds.includes(id)||progress.placedIds.includes(id))return;setProgress(value=>({...value,placedIds:value.placedIds.includes(id)?value.placedIds:[...value.placedIds,id]}));tone("place");setInspect(id);setPendingPlacementId(null);}
 const reward=session?.rewardId?collectible(session.rewardId):null,counts={first:outcomes.filter(x=>x==="first").length,retry:outcomes.filter(x=>x==="retry").length,reviewed:outcomes.filter(x=>x==="reviewed").length};
 const image=(name:string,children:React.ReactNode,label:string)=><section className={`stage image-stage ${name}`} aria-label={label}><img src={`/assets/${name}.png`} alt="" draggable={false}/>{children}</section>;
 return <main className="game-shell"><div className="grain" aria-hidden="true"/>
 {screen==="title"&&image("title",<>{completeToday&&<div className="completion-mark">TODAY’S ROOM REMEMBERS</div>}<button className="hotspot start-hotspot" onClick={()=>go("contents")} aria-label="Enter Neverending Math"/></>,"Neverending Math")}
 {screen==="contents"&&image("contents",<><button className="hotspot daily-hotspot" onClick={()=>begin(false)} aria-label="Begin today’s mathematics"/><button className="hotspot rewards-hotspot" onClick={()=>go("rewards")} aria-label="Open objects collection"/><button className="hotspot settings-hotspot" onClick={()=>go("settings")} aria-label="Open settings"/>{completeToday&&<><div className="daily-status">✓ TODAY COMPLETE · RETURN TOMORROW</div><button className="extra-practice" onClick={()=>begin(true)}>PRACTICE A LITTLE MORE</button></>}<button className="corner-back" onClick={()=>go("title")}>← TITLE</button></>,"Contents")}
 {screen==="warmupIntro"&&<section className="stage image-stage art-transition-stage warm-transition-stage"><img src="/assets/warmup-clean.png" alt=""/><div className="warm-transition-copy"><p>EIGHT QUICK FACTS.</p><p>SAY OR TYPE EACH ANSWER.</p></div><button className="art-chalk-button warm-transition-button" onClick={()=>{saveJourney("warmup");go("warmup");}}>BEGIN →</button></section>}
 {screen==="warmup"&&<section className="stage image-stage warm-art-stage"><img src="/assets/warmup-clean.png" alt=""/><p className="warm-live-count">{warmIndex+1} OF {warmups.length}</p><div className="warm-live-problem fact-medium">{warmups[warmIndex]?.prompt.replace(" = ?","")}</div><button className={`mic-hotspot ${listening?"listening":""}`} onClick={listen} aria-label="Use voice input" disabled={answerState==="review"||answerState==="advancing"}/><div className="voice-state" aria-live="polite"><strong>{feedback||"SAY IT ALOUD, OR TYPE IT BELOW"}</strong><span>{detail}</span></div><form className="warm-type-form" onSubmit={e=>{e.preventDefault();submitWarm();}}><input ref={inputRef} value={answer} onInput={e=>setAnswer(e.currentTarget.value)} onChange={e=>setAnswer(e.target.value)} inputMode="numeric" aria-label="Warm-up answer" disabled={answerState==="review"||answerState==="advancing"}/><button disabled={answerState==="advancing"}>{answerState==="review"?"CONTINUE →":"CHECK →"}</button></form></section>}
 {screen==="warmupComplete"&&<section className="stage image-stage art-transition-stage warm-transition-stage"><img src="/assets/warmup-clean.png" alt=""/><div className="warm-transition-copy complete"><h1>WARM-UP COMPLETE</h1><p>THE DAILY CHALLENGE IS READY.</p></div><button className="art-chalk-button warm-transition-button" onClick={()=>{saveJourney("challengeIntro");go("challengeIntro");}}>CONTINUE →</button></section>}
 {screen==="challengeIntro"&&<section className="stage image-stage art-transition-stage challenge-transition-stage"><img src="/assets/challenge-clean.png" alt=""/><div className="challenge-transition-copy"><p className="challenge-day">TODAY’S SESSION</p><h1>DAILY CHALLENGE</h1><p className="challenge-total">{session?.questions.length??12} QUESTIONS</p><p className="challenge-intro-note">Take your time. Difficult questions are meant to be worked out.</p></div><button className="art-chalk-button challenge-transition-button" onClick={()=>{saveJourney("challenge");go("challenge");}}>BEGIN →</button></section>}
 {screen==="challenge"&&activeQuestion&&<section className="stage image-stage challenge-art-stage"><img src="/assets/challenge-clean.png" alt=""/><div className="challenge-layout"><header className="challenge-meta"><p>QUESTION {questionIndex+1} OF {session?.questions.length}</p><p>— {activeQuestion.skill.replace(/([A-Z])/g," $1").toUpperCase()} —</p></header><div className="challenge-question" data-question-display={activeQuestionDisplay}>{activeQuestion.prompt}</div><div className="challenge-feedback" aria-live="polite"><strong>{feedback}</strong><span>{detail}</span></div><form className="challenge-answer-form" onSubmit={e=>{e.preventDefault();submitQuestion();}}><label htmlFor="main-answer">YOUR ANSWER</label><input id="main-answer" ref={inputRef} value={answer} onInput={e=>setAnswer(e.currentTarget.value)} onChange={e=>setAnswer(e.target.value)} autoComplete="off" inputMode={activeQuestion.input==="number"?"numeric":"text"} disabled={answerState==="review"||answerState==="advancing"}/><button disabled={answerState==="advancing"}>{answerState==="review"?"CONTINUE →":"CHECK ANSWER →"}</button></form>{activeQuestion.input==="factors"&&<p className="challenge-format-example">FORMAT: 2 × 2 × 3</p>}<button className="challenge-skip" disabled={answerState==="review"||answerState==="advancing"} onClick={showQuestionReview}>SKIP</button></div></section>}
 {screen==="results"&&<section className="stage chalk-stage results-stage"><p className="eyebrow">NEVERENDING MATH</p><h1>TODAY’S WORK<br/>IS COMPLETE</h1><div className="score-grid"><p><b>{counts.first}</b>CORRECT</p><p><b>{counts.retry}</b>SOLVED WITH<br/>ANOTHER TRY</p><p><b>{counts.reviewed}</b>REVIEWED</p></div><div className="completion-list"><span>{warmups.length?"✓ WARM-UP COMPLETE":"✓ WARM-UP NOT SCHEDULED"}</span><span>✓ DAILY CHALLENGE COMPLETE</span></div>{counts.reviewed>0&&<p className="review-note">A few ideas have been left on the board for another day.</p>}<p className="room-notice">{session?.extra?"The room remembers the extra care you gave it.":"The room has noticed your work."}</p><button className="chalk-button results-reward-button" onClick={receive}>{session?.extra?"RETURN TO THE STUDY →":"RECEIVE TODAY’S OBJECT →"}</button></section>}
 {screen==="reward"&&image("reward-clean",<><div className="reward-glow"/>{reward?.[0]!=="bell"&&<div className="reward-object-glyph" aria-hidden="true">{objectGlyphs[reward?.[0]??"bell"]}</div>}<div className="reward-name"><strong>{reward?.[1]}</strong><span>{reward?.[2]}</span></div><button className="reward-choice reward-continue" onClick={()=>go("rewards")}>CONTINUE TO OBJECTS COLLECTION →</button><button className="reward-choice reward-home" onClick={()=>go("title")}>GO HOME</button></>,"Object found")}
 {screen==="rewards"&&image("rewards",<><div className="empty-collection-board"><span>{progress.collectedIds.length?"OBJECTS FOUND":"THE SHELVES ARE QUIET"}</span></div><div className="found-count">{progress.collectedIds.length} FOUND</div><div className="collection-items" aria-label="Discovered objects">{progress.collectedIds.map((id,index)=>{const item=collectible(id),placed=progress.placedIds.includes(id);return <button key={id} data-collectible-id={id} className={`collection-item${inspect===id?" selected":""}${placed?" placed":""}`} onClick={()=>{setInspect(id);setPendingPlacementId(null);}} aria-label={`Inspect ${item[1]}`} aria-pressed={inspect===id}><strong>{String(index+1).padStart(2,"0")} · {item[1]}</strong>{placed&&<span>IN THE STUDY</span>}</button>})}</div>{inspect&&progress.collectedIds.includes(inspect)&&<div className="collection-selection-panel"><div className="collection-label"><strong>{collectible(inspect)[1]}</strong><span>{collectible(inspect)[2]}</span></div><button className="collection-study-button" onClick={()=>beginPlacement(inspect)}>{progress.placedIds.includes(inspect)?"VIEW IN THE STUDY →":"PLACE IN THE STUDY →"}</button></div>}<button className="hotspot rewards-back" onClick={()=>go("contents")} aria-label="Return to contents"/></>,"Objects collection")}
 {screen==="study"&&image("study-empty",<><div className="study-objects">{progress.placedIds.map((id,index)=><button key={id} className={`study-object study-object-${index%8}`} onClick={()=>{setInspect(id);setPendingPlacementId(null);}} aria-label={`Inspect ${collectible(id)[1]} in the Study`}>{collectible(id)[1]}</button>)}</div>{inspect&&progress.collectedIds.includes(inspect)&&<aside className={`study-placement-panel${pendingPlacementId===inspect?" pending":""}`} aria-live="polite"><div className="study-placement-details"><strong>{collectible(inspect)[1]}</strong><span>{collectible(inspect)[2]}</span>{progress.placedIds.includes(inspect)&&<em>IN THE STUDY</em>}</div>{pendingPlacementId===inspect&&<button className="study-place-button" onClick={()=>place(inspect)} aria-label={`Place ${collectible(inspect)[1]} in the Study`}>PLACE THIS IN THE STUDY →</button>}</aside>}<button className="hotspot study-back-hotspot" onClick={()=>{setPendingPlacementId(null);go("rewards");}} aria-label="Return to collection"/><button className="study-home" onClick={()=>{setPendingPlacementId(null);go("title");}}>GO HOME</button></>,"The Study")}
 {screen==="settings"&&image("settings",<><div className="concept-settings" aria-label="Active math concepts"><h2>ACTIVE MATH CONCEPTS</h2><p>Choose what may appear in future challenges.</p><div className="concept-groups">{skillGroups.map(group=><fieldset key={group.name}><legend>{group.name}</legend>{group.skills.map(skill=><label key={skill}><input type="checkbox" checked={progress.activeSkills.includes(skill)} disabled={progress.activeSkills.length===1&&progress.activeSkills.includes(skill)} onChange={()=>toggleSkill(skill)}/><span>{skillNames[skill]}</span></label>)}</fieldset>)}</div><p className="concept-note">Keep at least one concept active.</p></div><div className="settings-controls"><button onClick={()=>setProgress(v=>({...v,voice:!v.voice}))}>VOICE: {progress.voice?"ON":"OFF"}</button><button onClick={()=>setProgress(v=>({...v,sound:!v.sound}))}>SOUND: {progress.sound?"ON":"OFF"}</button></div><button className="hotspot settings-back" onClick={()=>go("contents")} aria-label="Back"/><button className="hotspot settings-save" onClick={()=>go("contents")} aria-label="Save settings"/></>,"Settings")}
 </main>;
}
